# Generated by Django 5.2.6 on 2025-09-26 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_department'),
        ('performance', '0002_alter_performance_options_performance_comments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performance',
            options={},
        ),
        migrations.AlterField(
            model_name='performance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
    ]
